In [16]:
import pandas as pd
import numpy as np

df = pd.read_csv("customers.csv")
df_bk=df

print("Dataset loaded successfully")

Dataset loaded successfully

In [17]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 20000
Columns: 18

In [18]:
print(df.shape)

(20000, 18)

In [19]:
df.head()

,customer_id,customer_signup_date,gender,age,age_group,state,city,pincode_prefix,customer_segment,preferred_device,preferred_payment_method,acquisition_channel,total_orders,total_spend,last_order_date,average_order_value,customer_status,loyalty_tier
0,CUST100000,2023-01-09,Male,44.0,35-44,Madhya Pradesh,Indore,607,Regular,Mobile App,EMI,Affiliate,3,36884.57,2023-05-26,12294.86,Churned,Bronze
1,CUST100001,2023-04-10,Male,20.0,18-24,West Bengal,Kolkata,245,Regular,Mobile App,Cash on Delivery,Organic Search,7,371585.73,2024-05-23,53083.68,Churned,Gold
2,CUST100002,2025-05-09,Female,35.0,35-44,Gujarat,Ahmedabad,160,Premium,Mobile Web,UPI,SMS Marketing,10,114901.74,2025-07-14,11490.17,At Risk,Silver
3,CUST100003,2024-12-24,Female,34.0,25-34,Maharashtra,Pune,175,New,Mobile App,UPI,Influencer Marketing,1,3788.82,2025-12-19,3788.82,Active,Bronze
4,CUST100004,2023-08-15,Male,38.0,35-44,Andhra Pradesh,Visakhapatnam,446,Budget,Desktop,Cash on Delivery,Referral,2,61295.90,2023-11-01,30647.95,Churned,Silver

In [20]:
df.tail()

,customer_id,customer_signup_date,gender,age,age_group,state,city,pincode_prefix,customer_segment,preferred_device,preferred_payment_method,acquisition_channel,total_orders,total_spend,last_order_date,average_order_value,customer_status,loyalty_tier
19995,CUST124989,2025-10-30,Male,24.0,18-24,Karnataka,Bengaluru,453,Regular,Desktop,Cash on Delivery,Email Marketing,7,83738.23,2025-12-30,11962.60,Active,Silver
19996,CUST124990,2024-10-31,Male,25.0,25-34,Bihar,Patna,313,Premium,Mobile Web,UPI,Organic Search,15,559946.63,2025-12-17,37329.78,Active,Platinum
19997,CUST124991,2023-10-28,Female,44.0,35-44,Rajasthan,Jaipur,504,Budget,Mobile App,EMI,Social Media - Instagram,1,186.50,2024-12-20,186.50,Churned,Bronze
19998,CUST124994,2023-03-12,Male,31.0,25-34,Maharashtra,Mumbai,731,Budget,Mobile App,UPI,Email Marketing,1,2454.90,2023-05-04,2454.90,Churned,Bronze
19999,CUST124997,2025-11-01,Male,18.0,18-24,Punjab,Ludhiana,668,Regular,Mobile App,UPI,Organic Search,4,197907.83,2025-12-12,49476.96,Active,Gold

In [21]:
print(df.columns.tolist())

['customer_id', 'customer_signup_date', 'gender', 'age', 'age_group', 'state', 'city', 'pincode_prefix', 'customer_segment', 'preferred_device', 'preferred_payment_method', 'acquisition_channel', 'total_orders', 'total_spend', 'last_order_date', 'average_order_value', 'customer_status', 'loyalty_tier']

In [22]:
column_report = pd.DataFrame({
    "Column": df.columns,
    "Data_Type": df.dtypes.values,
    "Missing_Count": df.isnull().sum().values,
    "Unique_Count": df.nunique().values
})

column_report

                      Column Data_Type  Missing_Count  Unique_Count
0                customer_id    object              0         20000
1       customer_signup_date    object              0          1096
2                     gender    object              0             3
3                        age   float64            202            49
4                  age_group    object              0             5
5                      state    object              0            15
6                       city    object              0            31
7             pincode_prefix     int64              0           800
8           customer_segment    object              0             4
9           preferred_device    object             97             3
10  preferred_payment_method    object              0            10
11       acquisition_channel    object              0            10
12              total_orders     int64              0            24
13               total_spend   float64              0         18469
14           last_order_date    object           1309          1073
15       average_order_value   float64              0         18440
16           customer_status    object              0             4
17              loyalty_tier    object              0             4

In [23]:
print(df.dtypes)

customer_id                  object
customer_signup_date         object
gender                       object
age                         float64
age_group                    object
state                        object
city                         object
pincode_prefix                int64
customer_segment             object
preferred_device             object
preferred_payment_method     object
acquisition_channel          object
total_orders                  int64
total_spend                 float64
last_order_date              object
average_order_value         float64
customer_status              object
loyalty_tier                 object
dtype: object

In [24]:
# Missing_count
missing_count = df.isnull().sum()

print(missing_count)

customer_id                    0
customer_signup_date           0
gender                         0
age                          202
age_group                      0
state                          0
city                           0
pincode_prefix                 0
customer_segment               0
preferred_device              97
preferred_payment_method       0
acquisition_channel            0
total_orders                   0
total_spend                    0
last_order_date             1309
average_order_value            0
customer_status                0
loyalty_tier                   0
dtype: int64

In [25]:
missing_percentage = (df.isnull().sum() / len(df)) * 100

missing_report = pd.DataFrame({
    "Missing_Count": df.isnull().sum(),
    "Missing_Percentage": missing_percentage
})

missing_report

                          Missing_Count  Missing_Percentage
customer_id                           0               0.000
customer_signup_date                  0               0.000
gender                                0               0.000
age                                 202               1.010
age_group                             0               0.000
state                                 0               0.000
city                                  0               0.000
pincode_prefix                        0               0.000
customer_segment                      0               0.000
preferred_device                     97               0.485
preferred_payment_method              0               0.000
acquisition_channel                   0               0.000
total_orders                          0               0.000
total_spend                           0               0.000
last_order_date                    1309               6.545
average_order_value                   0               0.000
customer_status                       0               0.000
loyalty_tier                          0               0.000

In [26]:
missing_report.sort_values(
    by="Missing_Percentage",
    ascending=False
)

                          Missing_Count  Missing_Percentage
last_order_date                    1309               6.545
age                                 202               1.010
preferred_device                     97               0.485
preferred_payment_method              0               0.000
customer_status                       0               0.000
average_order_value                   0               0.000
total_spend                           0               0.000
total_orders                          0               0.000
acquisition_channel                   0               0.000
customer_id                           0               0.000
customer_signup_date                  0               0.000
customer_segment                      0               0.000
pincode_prefix                        0               0.000
city                                  0               0.000
state                                 0               0.000
age_group                             0               0.000
gender                                0               0.000
loyalty_tier                          0               0.000

In [27]:
duplicate_count = df.duplicated().sum()

print("Duplicate rows:", duplicate_count)

Duplicate rows: 0

In [28]:
duplicates = df[df.duplicated(keep=False)]

duplicates.head(20)

Empty DataFrame
Columns: [customer_id, customer_signup_date, gender, age, age_group, state, city, pincode_prefix, customer_segment, preferred_device, preferred_payment_method, acquisition_channel, total_orders, total_spend, last_order_date, average_order_value, customer_status, loyalty_tier]
Index: []

In [29]:
df["customer_id"].duplicated().sum()

0

In [38]:
print("Gender Type : ",df["gender"].unique())
print("Customer_Status : ",df["customer_status"].unique())
print("Loyalty_tier : ",df["loyalty_tier"].unique())
print("Preffered Device type :",df["preferred_device"].unique())
print("Preferred_Payment_method",df["preferred_payment_method"].unique())
print(df["acquisition_channel"].unique())

Gender Type :  ['Male' 'Female' 'Other']
Customer_Status :  ['Churned' 'At Risk' 'Active' 'Never Purchased']
Loyalty_tier :  ['Bronze' 'Gold' 'Silver' 'Platinum']
Preffered Device type : ['Mobile App' 'Mobile Web' 'Desktop' nan]
Preferred_Payment_method ['EMI' 'Cash on Delivery' 'UPI' 'Credit Card' 'Wallet' 'Gift Card'
 'Net Banking' 'Pay Later' 'Debit Card' 'Cardless EMI']
['Affiliate' 'Organic Search' 'SMS Marketing' 'Influencer Marketing'
 'Referral' 'Direct/App' 'Email Marketing' 'Social Media - Instagram'
 'Social Media - Facebook' 'Paid Search']

In [39]:
for col in [
    "gender",
    "customer_status",
    "loyalty_tier",
    "preferred_device",
    "preferred_payment_method",
    "acquisition_channel"
]:
    print("\n", col)
    print(df[col].value_counts(dropna=False))

 gender
gender
Male      10710
Female     8868
Other       422
Name: count, dtype: int64

 customer_status
customer_status
Churned            10890
Active              6086
At Risk             1715
Never Purchased     1309
Name: count, dtype: int64

 loyalty_tier
loyalty_tier
Bronze      10379
Silver       5662
Gold         2950
Platinum     1009
Name: count, dtype: int64

 preferred_device
preferred_device
Mobile App    12403
Mobile Web     4538
Desktop        2962
NaN              97
Name: count, dtype: int64

 preferred_payment_method
preferred_payment_method
UPI                 6416
Cash on Delivery    3461
Credit Card         2979
Debit Card          2521
Net Banking         1618
Wallet              1427
EMI                  790
Pay Later            370
Gift Card            218
Cardless EMI         200
Name: count, dtype: int64

 acquisition_channel
acquisition_channel
Organic Search              4443
Paid Search                 2747
Direct/App                  2504
Social Media - Instagram    2357
Social Media - Facebook     1708
Email Marketing             1614
Affiliate                   1361
Referral                    1266
Influencer Marketing        1197
SMS Marketing                803
Name: count, dtype: int64

In [41]:
text_columns = df.select_dtypes(include="object").columns

for col in text_columns:
    df[col] = df[col].str.strip()

In [42]:
text_columns

Index(['customer_id', 'customer_signup_date', 'gender', 'age_group', 'state',
       'city', 'customer_segment', 'preferred_device',
       'preferred_payment_method', 'acquisition_channel', 'last_order_date',
       'customer_status', 'loyalty_tier'],
      dtype='object')

In [44]:
print(df["age"].describe())

count    19798.000000
mean        31.794525
std          8.507600
min         18.000000
25%         25.000000
50%         31.000000
75%         38.000000
max         67.000000
Name: age, dtype: float64

In [46]:
invalid_age = df[
    (df["age"] < 0) |
    (df["age"] > 120)
]

invalid_age

Empty DataFrame
Columns: [customer_id, customer_signup_date, gender, age, age_group, state, city, pincode_prefix, customer_segment, preferred_device, preferred_payment_method, acquisition_channel, total_orders, total_spend, last_order_date, average_order_value, customer_status, loyalty_tier]
Index: []

In [51]:
df[df["age"] <20]

,customer_id,customer_signup_date,gender,age,age_group,state,city,pincode_prefix,customer_segment,preferred_device,preferred_payment_method,acquisition_channel,total_orders,total_spend,last_order_date,average_order_value,customer_status,loyalty_tier
6,CUST100006,2023-01-24,Male,18.0,18-24,Kerala,Thiruvananthapuram,511,New,Mobile Web,Cash on Delivery,Direct/App,3,78978.17,2023-11-18,26326.06,Churned,Silver
51,CUST100051,2025-06-22,Male,18.0,18-24,Gujarat,Vadodara,520,Budget,Mobile App,Cash on Delivery,Affiliate,1,20058.88,2025-12-22,20058.88,Active,Bronze
78,CUST100078,2024-04-08,Female,18.0,18-24,Maharashtra,Pune,557,Budget,Desktop,Debit Card,Social Media - Facebook,1,12061.35,2024-11-04,12061.35,Churned,Bronze
96,CUST100096,2024-10-19,Female,18.0,18-24,Uttar Pradesh,Lucknow,516,Regular,Mobile App,UPI,Influencer Marketing,1,15922.30,2025-04-29,15922.30,Churned,Bronze
105,CUST100105,2023-11-29,Male,18.0,18-24,Telangana,Warangal,789,Budget,Mobile App,UPI,Organic Search,3,20733.72,2024-04-30,6911.24,Churned,Bronze
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19982,CUST124967,2023-01-11,Male,18.0,18-24,Telangana,Hyderabad,672,Regular,Mobile App,UPI,Organic Search,2,6576.89,2023-02-21,3288.44,Churned,Bronze
19985,CUST124972,2025-08-24,Male,19.0,18-24,Telangana,Warangal,468,Premium,Mobile App,Net Banking,Email Marketing,8,89140.22,2025-12-26,11142.53,Active,Silver
19991,CUST124983,2024-09-30,Female,18.0,18-24,Tamil Nadu,Chennai,143,Premium,Mobile Web,UPI,Organic Search,7,129114.52,2025-12-03,18444.93,Active,Silver
19994,CUST124986,2025-05-04,Male,18.0,18-24,Telangana,Hyderabad,218,Regular,Mobile App,Credit Card,Direct/App,2,43672.66,2025-10-18,21836.33,Active,Bronze
19999,CUST124997,2025-11-01,Male,18.0,18-24,Punjab,Ludhiana,668,Regular,Mobile App,UPI,Organic Search,4,197907.83,2025-12-12,49476.96,Active,Gold

In [53]:
numeric_columns = [
    "age",
    "total_orders",
    "total_spend",
    "average_order_value"
]

df[numeric_columns].describe()

                age  total_orders   total_spend  average_order_value
count  19798.000000  20000.000000  2.000000e+04         20000.000000
mean      31.794525      4.237900  1.070532e+05         21907.338433
std        8.507600      3.389244  1.346943e+05         25322.116993
min       18.000000      0.000000  0.000000e+00             0.000000
25%       25.000000      2.000000  1.434605e+04          6161.482500
50%       31.000000      3.000000  5.373706e+04         14535.680000
75%       38.000000      6.000000  1.515590e+05         29223.927500
max       67.000000     24.000000  1.157867e+06        381793.120000

In [56]:
df[df["total_orders"] < 0]

Empty DataFrame
Columns: [customer_id, customer_signup_date, gender, age, age_group, state, city, pincode_prefix, customer_segment, preferred_device, preferred_payment_method, acquisition_channel, total_orders, total_spend, last_order_date, average_order_value, customer_status, loyalty_tier]
Index: []

In [57]:
df[df["total_spend"] < 0]

Empty DataFrame
Columns: [customer_id, customer_signup_date, gender, age, age_group, state, city, pincode_prefix, customer_segment, preferred_device, preferred_payment_method, acquisition_channel, total_orders, total_spend, last_order_date, average_order_value, customer_status, loyalty_tier]
Index: []

In [58]:
df[df["average_order_value"] < 0]

Empty DataFrame
Columns: [customer_id, customer_signup_date, gender, age, age_group, state, city, pincode_prefix, customer_segment, preferred_device, preferred_payment_method, acquisition_channel, total_orders, total_spend, last_order_date, average_order_value, customer_status, loyalty_tier]
Index: []

In [63]:
# Check logical relationships

df[
    (df["total_orders"] == 0) &
    (df["last_order_date"].notna())
]

Empty DataFrame
Columns: [customer_id, customer_signup_date, gender, age, age_group, state, city, pincode_prefix, customer_segment, preferred_device, preferred_payment_method, acquisition_channel, total_orders, total_spend, last_order_date, average_order_value, customer_status, loyalty_tier]
Index: []

In [64]:
df[
    (df["total_orders"] > 0) &
    (df["last_order_date"].isna())
]

Empty DataFrame
Columns: [customer_id, customer_signup_date, gender, age, age_group, state, city, pincode_prefix, customer_segment, preferred_device, preferred_payment_method, acquisition_channel, total_orders, total_spend, last_order_date, average_order_value, customer_status, loyalty_tier]
Index: []

In [65]:
# Converting date columns  form object ->Date

In [66]:
df["customer_signup_date"] = pd.to_datetime(
    df["customer_signup_date"],
    errors="coerce"
)

df["last_order_date"] = pd.to_datetime(
    df["last_order_date"],
    errors="coerce"
)

In [68]:
print(df[[
    "customer_signup_date",
    "last_order_date"
]].dtypes)

customer_signup_date    datetime64[ns]
last_order_date         datetime64[ns]
dtype: object

In [70]:
print(df["customer_signup_date"].isna().sum())
print(df["last_order_date"].isna().sum())

0
1309

In [73]:
#Last order before signup
invalid_dates = df[
    df["last_order_date"] < df["customer_signup_date"]
]

invalid_dates

Empty DataFrame
Columns: [customer_id, customer_signup_date, gender, age, age_group, state, city, pincode_prefix, customer_segment, preferred_device, preferred_payment_method, acquisition_channel, total_orders, total_spend, last_order_date, average_order_value, customer_status, loyalty_tier]
Index: []

In [74]:
today = pd.Timestamp.today()

future_signup = df[
    df["customer_signup_date"] > today
]

future_signup

Empty DataFrame
Columns: [customer_id, customer_signup_date, gender, age, age_group, state, city, pincode_prefix, customer_segment, preferred_device, preferred_payment_method, acquisition_channel, total_orders, total_spend, last_order_date, average_order_value, customer_status, loyalty_tier]
Index: []

In [83]:
df["calculated_aov"] = np.where(
    df["total_orders"] > 0,
    df["total_spend"] / df["total_orders"],
    np.nan
)

df["calculated_aov"]

0        12294.856667
1        53083.675714
2        11490.174000
3         3788.820000
4        30647.950000
             ...
19995    11962.604286
19996    37329.775333
19997      186.500000
19998     2454.900000
19999    49476.957500
Name: calculated_aov, Length: 20000, dtype: float64

In [84]:
df[[
    "total_orders",
    "total_spend",
    "average_order_value",
    "calculated_aov"
]].head()

   total_orders  total_spend  average_order_value  calculated_aov
0             3     36884.57             12294.86    12294.856667
1             7    371585.73             53083.68    53083.675714
2            10    114901.74             11490.17    11490.174000
3             1      3788.82              3788.82     3788.820000
4             2     61295.90             30647.95    30647.950000

In [86]:
df["aov_difference"] = (
    df["average_order_value"] -
    df["calculated_aov"]
).abs()

In [87]:
df["aov_difference"]

0        0.003333
1        0.004286
2        0.004000
3        0.000000
4        0.000000
           ...
19995    0.004286
19996    0.004667
19997    0.000000
19998    0.000000
19999    0.002500
Name: aov_difference, Length: 20000, dtype: float64

In [88]:
# Outlier detection : 
Q1 = df["total_spend"].quantile(0.25)
Q3 = df["total_spend"].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers = df[
    (df["total_spend"] < lower_bound) |
    (df["total_spend"] > upper_bound)
]

print("Total spend outliers:", len(outliers))

Total spend outliers: 1246

# Report :

In [92]:
validation_report = pd.DataFrame({
    "check": [
        "Duplicate Rows",
        "Missing Values",
        "Duplicate Customer IDs",
        "Invalid Age",
        "Negative Total Orders",
        "Negative Total Spend",
        "Invalid Signup Dates",
        "Future Signup Dates"
    ],
    "result": [
        df.duplicated().sum(),
        df.isnull().sum().sum(),
        df["customer_id"].duplicated().sum(),
        ((df["age"] < 0) | (df["age"] > 120)).sum(),
        (df["total_orders"] < 0).sum(),
        (df["total_spend"] < 0).sum(),
        df["customer_signup_date"].isna().sum(),
        (df["customer_signup_date"] > pd.Timestamp.today()).sum()
    ]
})

validation_report

                    check  result
0          Duplicate Rows       0
1          Missing Values    4226
2  Duplicate Customer IDs       0
3             Invalid Age       0
4   Negative Total Orders       0
5    Negative Total Spend       0
6    Invalid Signup Dates       0
7     Future Signup Dates       0

In [93]:
validation_report["status"] = np.where(
    validation_report["result"] == 0,
    "PASS",
    "REVIEW"
)

validation_report

                    check  result  status
0          Duplicate Rows       0    PASS
1          Missing Values    4226  REVIEW
2  Duplicate Customer IDs       0    PASS
3             Invalid Age       0    PASS
4   Negative Total Orders       0    PASS
5    Negative Total Spend       0    PASS
6    Invalid Signup Dates       0    PASS
7     Future Signup Dates       0    PASS

In [94]:
df.to_csv(
    "customers_cleaned.csv",
    index=False
)

In [95]:
validation_report.to_csv(
    "customers_validation_report.csv",
    index=False
)