In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("customer_reviews.csv")

In [3]:
df.head()

,review_id,order_id,customer_id,product_id,review_date,rating,review_sentiment,verified_purchase
0,REV100000,ORD1000002,CUST120793,PROD10470,2024-12-30,4,Positive,True
1,REV100020,ORD1000022,CUST124473,PROD10392,2024-12-15,2,Negative,True
2,REV100021,ORD1000023,CUST119088,PROD10157,2025-11-14,3,Neutral,True
3,REV100030,ORD1000037,CUST105338,PROD10023,2025-11-12,4,Positive,True
4,REV100058,ORD1000075,CUST102107,PROD10403,2025-11-09,5,Positive,True

In [13]:
### dataset size
df.shape

(6503, 8)

In [14]:
### Check column names
df.columns

Index(['review_id', 'order_id', 'customer_id', 'product_id', 'review_date',
       'rating', 'review_sentiment', 'verified_purchase'],
      dtype='object')

In [15]:
### data types
df.dtypes

review_id            object
order_id             object
customer_id          object
product_id           object
review_date          object
rating                int64
review_sentiment     object
verified_purchase      bool
dtype: object

In [16]:
### Checking missing values
df.isnull().sum()

review_id             0
order_id              0
customer_id           0
product_id            0
review_date           0
rating                0
review_sentiment     12
verified_purchase     0
dtype: int64

In [17]:
### calculate in percentages
missing_percentage = (df.isnull().sum() / len(df)) * 100

missing_percentage

review_id            0.00000
order_id             0.00000
customer_id          0.00000
product_id           0.00000
review_date          0.00000
rating               0.00000
review_sentiment     0.18453
verified_purchase    0.00000
dtype: float64

In [18]:
### Checking duplicate records
df.duplicated().sum()

np.int64(0)

In [19]:
### inspect duplicates if they exist
df[df.duplicated()]

Empty DataFrame
Columns: [review_id, order_id, customer_id, product_id, review_date, rating, review_sentiment, verified_purchase]
Index: []

In [42]:
### Check unique values
### This is important for finding inconsistent categories

for column in df.columns:
    print("\n", column)
    print(df[column].unique()[:20])

### checking sentiment
df["review_sentiment"].value_counts(dropna=False)

 review_id
['REV100000' 'REV100020' 'REV100021' 'REV100030' 'REV100058' 'REV100061'
 'REV100062' 'REV100075' 'REV100085' 'REV100103' 'REV100110' 'REV100122'
 'REV100150' 'REV100164' 'REV100165' 'REV100166' 'REV100167' 'REV100175'
 'REV100176' 'REV100188']

 order_id
['ORD1000002' 'ORD1000022' 'ORD1000023' 'ORD1000037' 'ORD1000075'
 'ORD1000077' 'ORD1000078' 'ORD1000096' 'ORD1000107' 'ORD1000130'
 'ORD1000139' 'ORD1000152' 'ORD1000186' 'ORD1000216' 'ORD1000217'
 'ORD1000219' 'ORD1000223' 'ORD1000234' 'ORD1000235' 'ORD1000254']

 customer_id
['CUST120793' 'CUST124473' 'CUST119088' 'CUST105338' 'CUST102107'
 'CUST111941' 'CUST107376' 'CUST103202' 'CUST124402' 'CUST106293'
 'CUST114018' 'CUST123327' 'CUST103917' 'CUST103222' 'CUST119887'
 'CUST117107' 'CUST117396' 'CUST113266' 'CUST112241' 'CUST101818']

 product_id
['PROD10470' 'PROD10392' 'PROD10157' 'PROD10023' 'PROD10403' 'PROD10343'
 'PROD10418' 'PROD10528' 'PROD10374' 'PROD10501' 'PROD10211' 'PROD10135'
 'PROD10246' 'PROD10473' 'PROD10488' 'PROD10266' 'PROD10469' 'PROD10503'
 'PROD10245' 'PROD10147']

 review_date
<DatetimeArray>
['2024-12-30 00:00:00', '2024-12-15 00:00:00', '2025-11-14 00:00:00',
 '2025-11-12 00:00:00', '2025-11-09 00:00:00', '2023-07-24 00:00:00',
 '2025-04-12 00:00:00', '2023-08-07 00:00:00', '2024-05-18 00:00:00',
 '2024-05-08 00:00:00', '2025-12-31 00:00:00', '2025-12-01 00:00:00',
 '2024-05-04 00:00:00', '2023-06-13 00:00:00', '2025-10-07 00:00:00',
 '2025-11-27 00:00:00', '2024-06-19 00:00:00', '2023-05-13 00:00:00',
 '2024-04-29 00:00:00', '2025-11-23 00:00:00']
Length: 20, dtype: datetime64[ns]

 rating
[4 2 3 5 1]

 review_sentiment
['Positive' 'Negative' 'Neutral' nan]

 verified_purchase
[ True False]

review_sentiment
Positive    3843
Neutral     2044
Negative     604
NaN           12
Name: count, dtype: int64

In [21]:
### Validating the rating values
df["rating"].unique()

array([4, 2, 3, 5, 1])

In [22]:
df["rating"].value_counts().sort_index()

rating
1      59
2     545
3    2050
4    2573
5    1276
Name: count, dtype: int64

In [23]:
### If invalid values are found, don't automatically delete them.
### Instead, identify and report them.

df[(df["rating"] < 1) | (df["rating"] > 5)]

Empty DataFrame
Columns: [review_id, order_id, customer_id, product_id, review_date, rating, review_sentiment, verified_purchase]
Index: []

In [26]:
#### Converting review date to datetime. 
### if now - review_date - object

df["review_date"] = pd.to_datetime(df["review_date"], errors="coerce")

In [27]:
### After converting, review_date - datetime64[ns]
df.dtypes

review_id                    object
order_id                     object
customer_id                  object
product_id                   object
review_date          datetime64[ns]
rating                        int64
review_sentiment             object
verified_purchase              bool
dtype: object

In [29]:
### identify invalid dates

df[df["review_date"].isna()]

Empty DataFrame
Columns: [review_id, order_id, customer_id, product_id, review_date, rating, review_sentiment, verified_purchase]
Index: []

In [34]:
### Validate review dates
### Checking the overall date range.

print("Minimum date:", df["review_date"].min())
print("Maximum date:", df["review_date"].max())

Minimum date: 2023-01-13 00:00:00
Maximum date: 2025-12-31 00:00:00

In [35]:
df.head()

,review_id,order_id,customer_id,product_id,review_date,rating,review_sentiment,verified_purchase
0,REV100000,ORD1000002,CUST120793,PROD10470,2024-12-30,4,Positive,True
1,REV100020,ORD1000022,CUST124473,PROD10392,2024-12-15,2,Negative,True
2,REV100021,ORD1000023,CUST119088,PROD10157,2025-11-14,3,Neutral,True
3,REV100030,ORD1000037,CUST105338,PROD10023,2025-11-12,4,Positive,True
4,REV100058,ORD1000075,CUST102107,PROD10403,2025-11-09,5,Positive,True

In [36]:
### Checking text columns for unwanted spaces.

df["review_sentiment"].dropna().str.strip().unique()

array(['Positive', 'Negative', 'Neutral'], dtype=object)

In [37]:
### Standardize them without touching NaN values.

df["review_sentiment"] = df["review_sentiment"].str.strip()

In [43]:
### Standardize sentiment values.
### inspect first

df["review_sentiment"].value_counts(dropna=False)

review_sentiment
Positive    3843
Neutral     2044
Negative     604
NaN           12
Name: count, dtype: int64

In [44]:
### verifying these are the only expected categories: 

valid_sentiments = ["Positive", "Negative", "Neutral"]

invalid_sentiments = df[
    ~df["review_sentiment"].isin(valid_sentiments) &
    df["review_sentiment"].notna()
]

invalid_sentiments

Empty DataFrame
Columns: [review_id, order_id, customer_id, product_id, review_date, rating, review_sentiment, verified_purchase]
Index: []

In [45]:
### Validate verified_purchase

df["verified_purchase"].value_counts(dropna=False)

verified_purchase
True     6323
False     180
Name: count, dtype: int64

In [46]:
### Checking for unexpected values

df["verified_purchase"].unique()

array([ True, False])

In [47]:
### Validate IDs
### Checking whether IDs are missing:

df[["review_id", "order_id", "customer_id", "product_id"]].isnull().sum()

review_id      0
order_id       0
customer_id    0
product_id     0
dtype: int64

In [50]:
### check the number of unique IDs:

print("Unique reviews:", df["review_id"].nunique())
print("Unique orders:", df["order_id"].nunique())
print("Unique customers:", df["customer_id"].nunique())
print("Unique products:", df["product_id"].nunique())

Unique reviews: 6503
Unique orders: 6503
Unique customers: 5609
Unique products: 511

In [52]:
### checking the number of unique IDs:

df["review_id"].duplicated().sum()

np.int64(0)

In [53]:
df["order_id"].duplicated().sum()

np.int64(0)

In [54]:
df["customer_id"].duplicated().sum()

np.int64(894)

In [55]:
df["product_id"].duplicated().sum()

np.int64(5992)

In [56]:
### Generate a complete data-quality report:

quality_report = pd.DataFrame({
    "Column": df.columns,
    "Data_Type": df.dtypes.astype(str).values,
    "Missing_Values": df.isnull().sum().values,
    "Missing_Percentage": (
        df.isnull().sum().values / len(df) * 100
    ),
    "Unique_Values": df.nunique(dropna=True).values
})

quality_report

,Column,Data_Type,Missing_Values,Missing_Percentage,Unique_Values
0,review_id,object,0,0.00000,6503
1,order_id,object,0,0.00000,6503
2,customer_id,object,0,0.00000,5609
3,product_id,object,0,0.00000,511
4,review_date,datetime64[ns],0,0.00000,1055
5,rating,int64,0,0.00000,5
6,review_sentiment,object,12,0.18453,3
7,verified_purchase,bool,0,0.00000,2

In [59]:
### Statistical validation:
### numerical columns

df.describe()

                         review_date       rating
count                           6503  6503.000000
mean   2024-10-22 03:30:35.153006336     3.686145
min              2023-01-13 00:00:00     1.000000
25%              2023-12-22 00:00:00     3.000000
50%              2024-11-26 00:00:00     4.000000
75%              2025-09-07 00:00:00     4.000000
max              2025-12-31 00:00:00     5.000000
std                              NaN     0.911023

In [60]:
### For all columns:

df.describe(include="all")

,review_id,order_id,customer_id,product_id,review_date,rating,review_sentiment,verified_purchase
count,6503,6503,6503,6503,6503,6503.000000,6491,6503
unique,6503,6503,5609,511,NaN,NaN,3,2
top,REV100000,ORD1000002,CUST124757,PROD10403,NaN,NaN,Positive,True
freq,1,1,5,190,NaN,NaN,3843,6323
mean,NaN,NaN,NaN,NaN,2024-10-22 03:30:35.153006336,3.686145,NaN,NaN
min,NaN,NaN,NaN,NaN,2023-01-13 00:00:00,1.000000,NaN,NaN
25%,NaN,NaN,NaN,NaN,2023-12-22 00:00:00,3.000000,NaN,NaN
50%,NaN,NaN,NaN,NaN,2024-11-26 00:00:00,4.000000,NaN,NaN
75%,NaN,NaN,NaN,NaN,2025-09-07 00:00:00,4.000000,NaN,NaN
max,NaN,NaN,NaN,NaN,2025-12-31 00:00:00,5.000000,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,0.911023,NaN,NaN

In [61]:
### rating specifically:

df["rating"].describe()

count    6503.000000
mean        3.686145
std         0.911023
min         1.000000
25%         3.000000
50%         4.000000
75%         4.000000
max         5.000000
Name: rating, dtype: float64

In [62]:
### Check the final dataset:

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6503 entries, 0 to 6502
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   review_id          6503 non-null   object
 1   order_id           6503 non-null   object
 2   customer_id        6503 non-null   object
 3   product_id         6503 non-null   object
 4   review_date        6503 non-null   datetime64[ns]
 5   rating             6503 non-null   int64
 6   review_sentiment   6491 non-null   object
 7   verified_purchase  6503 non-null   bool
dtypes: bool(1), datetime64[ns](1), int64(1), object(5)
memory usage: 362.1+ KB

In [63]:
df.head()

,review_id,order_id,customer_id,product_id,review_date,rating,review_sentiment,verified_purchase
0,REV100000,ORD1000002,CUST120793,PROD10470,2024-12-30,4,Positive,True
1,REV100020,ORD1000022,CUST124473,PROD10392,2024-12-15,2,Negative,True
2,REV100021,ORD1000023,CUST119088,PROD10157,2025-11-14,3,Neutral,True
3,REV100030,ORD1000037,CUST105338,PROD10023,2025-11-12,4,Positive,True
4,REV100058,ORD1000075,CUST102107,PROD10403,2025-11-09,5,Positive,True

In [64]:
df.tail()

,review_id,order_id,customer_id,product_id,review_date,rating,review_sentiment,verified_purchase
6498,REV177468,ORD1099922,CUST102615,PROD10176,2023-11-08,5,Positive,True
6499,REV177484,ORD1099947,CUST117417,PROD10101,2024-12-22,3,Neutral,True
6500,REV177489,ORD1099953,CUST111326,PROD10077,2023-07-05,4,Positive,True
6501,REV177502,ORD1099968,CUST121344,PROD10125,2024-03-06,4,Positive,True
6502,REV177507,ORD1099979,CUST111852,PROD10403,2025-11-27,4,Positive,True

In [67]:
### Save the cleaned dataset:

df.to_csv("customer_reviews_cleaned.csv", index=False)

In [66]:
df.shape

(6503, 8)