In [1]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)

In [2]:
df = pd.read_csv("orders.csv")

print("Dataset loaded successfully")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Dataset loaded successfully
Rows: 20000
Columns: 16

In [3]:
df_original = df.copy()

print("Original dataset backup created.")

Original dataset backup created.

In [4]:
df.head()

,order_id,customer_id,order_date,order_time,order_status,shipping_method,delivery_city,delivery_state,coupon_code,discount_percentage,marketing_channel,subtotal,shipping_fee,tax_amount,final_amount,campaign_id
0,ORD1000002,CUST120793,2024-12-14,11:08:38,Delivered,Economy/Surface,Nagpur,Maharashtra,APP5,30.0,Social Media - Instagram,826.0,0.0,41.30,867.30,CAMP1101
1,ORD1000009,CUST117396,2024-05-26,23:17:31,Failed,Same-Day,Jodhpur,Rajasthan,FLAT50,20.0,Organic Search,2094.4,0.0,104.72,2199.12,NaN
2,ORD1000014,CUST103523,2023-07-21,14:50:17,Delivered,Express,Vijayawada,Andhra Pradesh,WELCOME10,15.0,Influencer Marketing,1326.0,0.0,66.30,1392.30,NaN
3,ORD1000020,CUST107722,2023-09-22,19:10:24,Delivered,Same-Day,Nagpur,Maharashtra,NEW100,5.0,Social Media - Facebook,5785.5,0.0,289.28,6074.78,NaN
4,ORD1000022,CUST124473,2024-11-24,06:04:26,Delivered,Standard,Ahmedabad,Gujarat,NaN,0.0,Paid Search,24531.3,0.0,1226.56,25757.86,NaN

In [5]:
df.tail()

,order_id,customer_id,order_date,order_time,order_status,shipping_method,delivery_city,delivery_state,coupon_code,discount_percentage,marketing_channel,subtotal,shipping_fee,tax_amount,final_amount,campaign_id
19995,ORD1099972,CUST107515,2025-10-18,16:15:41,Cancelled,Standard,Warangal,Telangana,NEW100,15.0,Social Media - Instagram,7183.2,0.0,359.16,7542.36,NaN
19996,ORD1099974,CUST100427,2023-08-28,17:07:46,Delivered,Standard,Ahmedabad,Gujarat,FLAT50,30.0,Direct/App,3877.1,0.0,193.86,4070.96,NaN
19997,ORD1099978,CUST124947,2023-02-14,17:20:44,Delivered,Standard,Hyderabad,Telangana,NaN,0.0,Social Media - Facebook,6000.0,0.0,300.00,6300.00,CAMP1008
19998,ORD1099979,CUST111852,2025-11-19,15:46:17,Delivered,Standard,Warangal,Telangana,NaN,0.0,SMS Marketing,1969.1,0.0,98.46,2067.56,NaN
19999,ORD1099980,CUST123614,2024-12-20,16:00:00,Returned,Next-Day,Lucknow,Uttar Pradesh,FEST20,30.0,Influencer Marketing,140.0,79.0,7.00,226.00,NaN

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   order_id             20000 non-null  str
 1   customer_id          20000 non-null  str
 2   order_date           20000 non-null  str
 3   order_time           20000 non-null  str
 4   order_status         20000 non-null  str
 5   shipping_method      20000 non-null  str
 6   delivery_city        20000 non-null  str
 7   delivery_state       20000 non-null  str
 8   coupon_code          13137 non-null  str
 9   discount_percentage  20000 non-null  float64
 10  marketing_channel    20000 non-null  str
 11  subtotal             20000 non-null  float64
 12  shipping_fee         20000 non-null  float64
 13  tax_amount           20000 non-null  float64
 14  final_amount         20000 non-null  float64
 15  campaign_id          3538 non-null   str
dtypes: float64(5), str(11)
memory usage: 4.2 MB

In [7]:
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

Number of rows: 20000
Number of columns: 16

In [8]:
print(df.columns.tolist())

['order_id', 'customer_id', 'order_date', 'order_time', 'order_status', 'shipping_method', 'delivery_city', 'delivery_state', 'coupon_code', 'discount_percentage', 'marketing_channel', 'subtotal', 'shipping_fee', 'tax_amount', 'final_amount', 'campaign_id']

In [9]:
df.columns = df.columns.str.strip()

In [10]:
missing_report = pd.DataFrame({
    "Missing_Count": df.isna().sum(),
    "Missing_Percentage": (
        df.isna().sum() / len(df) * 100
    ).round(2)
})

missing_report

                     Missing_Count  Missing_Percentage
order_id                         0                0.00
customer_id                      0                0.00
order_date                       0                0.00
order_time                       0                0.00
order_status                     0                0.00
shipping_method                  0                0.00
delivery_city                    0                0.00
delivery_state                   0                0.00
coupon_code                   6863               34.32
discount_percentage              0                0.00
marketing_channel                0                0.00
subtotal                         0                0.00
shipping_fee                     0                0.00
tax_amount                       0                0.00
final_amount                     0                0.00
campaign_id                  16462               82.31

In [11]:
duplicate_count = df.duplicated().sum()

print("Duplicate rows:", duplicate_count)

Duplicate rows: 0

In [12]:
df.dtypes

order_id                   str
customer_id                str
order_date                 str
order_time                 str
order_status               str
shipping_method            str
delivery_city              str
delivery_state             str
coupon_code                str
discount_percentage    float64
marketing_channel          str
subtotal               float64
shipping_fee           float64
tax_amount             float64
final_amount           float64
campaign_id                str
dtype: object

In [13]:
text_columns = df.select_dtypes(include="object").columns

for col in text_columns:
    df[col] = df[col].str.strip()

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_9092\3659800821.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_columns = df.select_dtypes(include="object").columns

In [14]:
text_columns = df.select_dtypes(include="object").columns

for col in text_columns:
    df[col] = df[col].str.strip()

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_9092\3659800821.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_columns = df.select_dtypes(include="object").columns

In [15]:
text_columns = df.select_dtypes(include="str").columns

for col in text_columns:
    df[col] = df[col].str.strip()

In [16]:
print("Text formatting completed successfully.")

Text formatting completed successfully.

In [19]:
print("Rows:", len(df))
print("NaN values:", df.isna().sum().sum())
print("Duplicate rows:", df.duplicated().sum())

Rows: 20000
NaN values: 23325
Duplicate rows: 0

In [23]:
categorical_columns = [
    "order_status",
    "shipping_method",
    "delivery_city",
    "delivery_state",
    "coupon_code",
    "marketing_channel"
]

for col in categorical_columns:
    print("\n" + "=" * 50)
    print("COLUMN:", col)
    print("=" * 50)
    print(df[col].value_counts(dropna=False))

==================================================
COLUMN: order_status
==================================================
order_status
Delivered     17261
Returned       1432
Cancelled       943
Failed          230
Processing      134
Name: count, dtype: int64

==================================================
COLUMN: shipping_method
==================================================
shipping_method
Standard           8974
Express            4068
Next-Day           3044
Economy/Surface    2898
Same-Day           1016
Name: count, dtype: int64

==================================================
COLUMN: delivery_city
==================================================
delivery_city
Pune                  958
New Delhi             945
Nagpur                940
Mumbai                908
Mysuru                822
Chennai               808
Coimbatore            807
Bengaluru             799
Ahmedabad             749
Lucknow               726
Warangal              712
Noida                 700
Vadodara              661
Surat                 661
Kanpur                656
Faridabad             652
Hyderabad             623
Gurugram              592
Howrah                591
Jodhpur               559
Kolkata               555
Thiruvananthapuram    531
Kochi                 525
Vijayawada            514
Visakhapatnam         490
Bhopal                469
Indore                455
Ludhiana              444
Jaipur                411
Amritsar              410
Patna                 327
Name: count, dtype: int64

==================================================
COLUMN: delivery_state
==================================================
delivery_state
Maharashtra       2806
Uttar Pradesh     2082
Gujarat           2071
Karnataka         1621
Tamil Nadu        1615
Telangana         1335
Haryana           1244
West Bengal       1146
Kerala            1056
Andhra Pradesh    1004
Rajasthan          970
Delhi              945
Madhya Pradesh     924
Punjab             854
Bihar              327
Name: count, dtype: int64

==================================================
COLUMN: coupon_code
==================================================
coupon_code
NaN           6863
WELCOME10     1695
FEST20        1678
APP5          1639
SAVE15        1636
FLAT50        1629
FREESHIP      1625
NEW100        1618
BIGBILLION    1617
Name: count, dtype: int64

==================================================
COLUMN: marketing_channel
==================================================
marketing_channel
Organic Search              4502
Direct/App                  2843
Paid Search                 2586
Social Media - Instagram    2219
Email Marketing             1691
Social Media - Facebook     1599
Referral                    1434
Affiliate                   1288
Influencer Marketing        1134
SMS Marketing                704
Name: count, dtype: int64

In [24]:
id="9v2n0q"
for col in categorical_columns:
    print(
        col,
        "→",
        df[col].notna().sum(),
        "non-missing +",
        df[col].isna().sum(),
        "NaN =",
        len(df)
    )

order_status → 20000 non-missing + 0 NaN = 20000
shipping_method → 20000 non-missing + 0 NaN = 20000
delivery_city → 20000 non-missing + 0 NaN = 20000
delivery_state → 20000 non-missing + 0 NaN = 20000
coupon_code → 13137 non-missing + 6863 NaN = 20000
marketing_channel → 20000 non-missing + 0 NaN = 20000

In [25]:
print("Total Order IDs:", df["order_id"].notna().sum())
print("Missing Order IDs:", df["order_id"].isna().sum())
print("Unique Order IDs:", df["order_id"].nunique(dropna=True))
print("Duplicate Order IDs:", df["order_id"].duplicated().sum())

Total Order IDs: 20000
Missing Order IDs: 0
Unique Order IDs: 20000
Duplicate Order IDs: 0

In [26]:
invalid_order_ids = ~df["order_id"].str.startswith(
    "ORD",
    na=False
)

print("Invalid Order ID format:", invalid_order_ids.sum())

Invalid Order ID format: 0

In [27]:
print("Total Customer IDs:", df["customer_id"].notna().sum())
print("Missing Customer IDs:", df["customer_id"].isna().sum())
print("Unique Customer IDs:", df["customer_id"].nunique(dropna=True))
print("Duplicate Customer IDs:", df["customer_id"].duplicated().sum())

Total Customer IDs: 20000
Missing Customer IDs: 0
Unique Customer IDs: 13145
Duplicate Customer IDs: 6855

In [28]:
invalid_customer_ids = ~df["customer_id"].str.startswith(
    "CUST",
    na=False
)

print("Invalid Customer ID format:", invalid_customer_ids.sum())

Invalid Customer ID format: 0

In [29]:
print("Data type before conversion:")
print(df["order_date"].dtype)

print("\nMissing dates:")
print(df["order_date"].isna().sum())

print("\nFirst 10 dates:")
print(df["order_date"].head(10))

Data type before conversion:
str

Missing dates:
0

First 10 dates:
0    2024-12-14
1    2024-05-26
2    2023-07-21
3    2023-09-22
4    2024-11-24
5    2025-10-28
6    2024-04-23
7    2023-05-07
8    2025-11-03
9    2025-10-22
Name: order_date, dtype: str

In [30]:
df["order_date"] = pd.to_datetime(
    df["order_date"],
    errors="coerce"
)

print("Data type after conversion:")
print(df["order_date"].dtype)

Data type after conversion:
datetime64[us]

In [31]:
print("Missing/invalid dates:", df["order_date"].isna().sum())

Missing/invalid dates: 0

In [32]:
print("Earliest order date:", df["order_date"].min())
print("Latest order date:", df["order_date"].max())

Earliest order date: 2023-01-02 00:00:00
Latest order date: 2025-12-31 00:00:00

In [33]:
print(df["order_date"].head(10))

0   2024-12-14
1   2024-05-26
2   2023-07-21
3   2023-09-22
4   2024-11-24
5   2025-10-28
6   2024-04-23
7   2023-05-07
8   2025-11-03
9   2025-10-22
Name: order_date, dtype: datetime64[us]

In [34]:
print("Data type before conversion:")
print(df["order_time"].dtype)

print("\nMissing order times:")
print(df["order_time"].isna().sum())

print("\nFirst 10 order times:")
print(df["order_time"].head(10))

Data type before conversion:
str

Missing order times:
0

First 10 order times:
0    11:08:38
1    23:17:31
2    14:50:17
3    19:10:24
4    06:04:26
5    18:20:05
6    19:07:08
7    20:48:09
8    17:13:05
9    23:15:20
Name: order_time, dtype: str

In [35]:
df["order_time"] = pd.to_datetime(
    df["order_time"],
    format="%H:%M:%S",
    errors="coerce"
).dt.time

print("Order time conversion completed.")
print(df["order_time"].head(10))

Order time conversion completed.
0    11:08:38
1    23:17:31
2    14:50:17
3    19:10:24
4    06:04:26
5    18:20:05
6    19:07:08
7    20:48:09
8    17:13:05
9    23:15:20
Name: order_time, dtype: object

In [36]:
print(
    "Missing/invalid order times:",
    df["order_time"].isna().sum()
)

Missing/invalid order times: 0

In [37]:
numeric_columns = [
    "discount_percentage",
    "subtotal",
    "shipping_fee",
    "tax_amount",
    "final_amount"
]

print(df[numeric_columns].dtypes)

discount_percentage    float64
subtotal               float64
shipping_fee           float64
tax_amount             float64
final_amount           float64
dtype: object

In [38]:
df[numeric_columns].describe()

,discount_percentage,subtotal,shipping_fee,tax_amount,final_amount
count,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000
mean,11.898000,9703.989535,8.608100,485.199685,10197.797320
std,10.737358,25417.798738,24.723846,1270.889923,26685.512175
min,0.000000,33.500000,0.000000,1.680000,78.880000
25%,0.000000,900.675000,0.000000,45.030000,945.705000
50%,10.000000,2299.000000,0.000000,114.950000,2413.950000
75%,20.000000,6362.000000,0.000000,318.100000,6680.100000
max,30.000000,449278.200000,149.000000,22463.910000,471742.110000

In [39]:
for col in [
    "subtotal",
    "shipping_fee",
    "tax_amount",
    "final_amount"
]:
    print(
        col,
        "→ Negative values:",
        (df[col] < 0).sum()
    )

subtotal → Negative values: 0
shipping_fee → Negative values: 0
tax_amount → Negative values: 0
final_amount → Negative values: 0

In [40]:
invalid_discount = (
    (df["discount_percentage"] < 0) |
    (df["discount_percentage"] > 100)
)

print("Invalid discount values:", invalid_discount.sum())

Invalid discount values: 0

In [41]:
id="5x7k2m"
calculated_final = (
    df["subtotal"]
    - (df["subtotal"] * df["discount_percentage"] / 100)
    + df["shipping_fee"]
    + df["tax_amount"]
)

difference = (df["final_amount"] - calculated_final).round(2)

print("Rows matching calculated final amount:", (difference == 0).sum())
print("Rows with differences:", (difference != 0).sum())
print("Maximum difference:", difference.abs().max())

Rows matching calculated final amount: 6390
Rows with differences: 13610
Maximum difference: 79821.0

In [42]:
print("Missing Campaign IDs:", df["campaign_id"].isna().sum())
print("Unique Campaign IDs:", df["campaign_id"].nunique(dropna=True))

print("\nCampaign ID sample:")
print(df["campaign_id"].value_counts(dropna=False).head(20))

Missing Campaign IDs: 16462
Unique Campaign IDs: 150

Campaign ID sample:
campaign_id
NaN         16462
CAMP1151      139
CAMP1147       70
CAMP1145       67
CAMP1144       65
CAMP1127       63
CAMP1117       58
CAMP1143       58
CAMP1132       55
CAMP1142       54
CAMP1150       53
CAMP1071       52
CAMP1092       50
CAMP1112       46
CAMP1082       44
CAMP1134       44
CAMP1094       43
CAMP1041       42
CAMP1077       41
CAMP1099       40
Name: count, dtype: int64

In [43]:
campaign_mask = df["campaign_id"].notna()

invalid_campaign_ids = (
    campaign_mask &
    ~df["campaign_id"].str.startswith("CAMP", na=False)
)

print("Invalid Campaign ID format:", invalid_campaign_ids.sum())

Invalid Campaign ID format: 0

In [44]:
id="q2m8vx"
print("Original shape:", df_original.shape)
print("Current shape:", df.shape)

print("\nRows removed:", df_original.shape[0] - df.shape[0])
print("Columns removed:", df_original.shape[1] - df.shape[1])

print("\nCurrent duplicate rows:", df.duplicated().sum())
print("Current total missing values:", df.isna().sum().sum())

Original shape: (20000, 16)
Current shape: (20000, 16)

Rows removed: 0
Columns removed: 0

Current duplicate rows: 0
Current total missing values: 23325

In [45]:
df.to_csv("orders_cleaned.csv", index=False)

print("orders_cleaned.csv created successfully")

orders_cleaned.csv created successfully

In [46]:
import os

print("File exists:", os.path.exists("orders_cleaned.csv"))
print("File size:", os.path.getsize("orders_cleaned.csv"), "bytes")

File exists: True
File size: 2689419 bytes