In [1]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)

df = pd.read_csv("payments.csv")

print("Dataset loaded successfully")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Dataset loaded successfully
Rows: 20000
Columns: 8

In [2]:
df_original = df.copy()

print("Original backup created successfully")
print("Backup rows:", df_original.shape[0])
print("Backup columns:", df_original.shape[1])

Original backup created successfully
Backup rows: 20000
Backup columns: 8

In [3]:
print("Column names:")
print(df.columns.tolist())

print("\nFirst 5 rows:")
display(df.head())

print("\nLast 5 rows:")
display(df.tail())

print("\nDataset information:")
df.info()

Column names:
['payment_id', 'order_id', 'payment_date', 'payment_method', 'payment_status', 'amount_paid', 'transaction_fee', 'refund_amount']

First 5 rows:

,payment_id,order_id,payment_date,payment_method,payment_status,amount_paid,transaction_fee,refund_amount
0,PAY1000002,ORD1000002,2024-12-14,Net Banking,Success,867.30,0.00,0.0
1,PAY1000009,ORD1000009,2024-05-26,Net Banking,Failed,0.00,0.00,0.0
2,PAY1000014,ORD1000014,2023-07-22,UPI,Success,1392.30,0.00,0.0
3,PAY1000020,ORD1000020,2023-09-22,Credit Card,Success,6074.78,91.12,0.0
4,PAY1000022,ORD1000022,2024-11-24,Cash on Delivery,Success,25757.86,0.00,0.0

Last 5 rows:

,payment_id,order_id,payment_date,payment_method,payment_status,amount_paid,transaction_fee,refund_amount
19995,PAY1099972,ORD1099972,2025-10-19,UPI,Refunded,7542.36,0.00,7542.36
19996,PAY1099974,ORD1099974,2023-08-28,Cash on Delivery,Success,4070.96,0.00,0.00
19997,PAY1099978,ORD1099978,2023-02-14,Cash on Delivery,Success,6300.00,0.00,0.00
19998,PAY1099979,ORD1099979,2025-11-20,Debit Card,Success,2067.56,0.00,0.00
19999,PAY1099980,ORD1099980,2024-12-21,Credit Card,Refunded,226.00,3.39,226.00

Dataset information:
<class 'pandas.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   payment_id       20000 non-null  str
 1   order_id         20000 non-null  str
 2   payment_date     20000 non-null  str
 3   payment_method   20000 non-null  str
 4   payment_status   20000 non-null  str
 5   amount_paid      20000 non-null  float64
 6   transaction_fee  20000 non-null  float64
 7   refund_amount    20000 non-null  float64
dtypes: float64(3), str(5)
memory usage: 2.1 MB

In [4]:
missing_report = pd.DataFrame({
    "Missing_Count": df.isna().sum(),
    "Missing_Percentage": (
        df.isna().sum() / len(df) * 100
    ).round(2)
})

missing_report

                 Missing_Count  Missing_Percentage
payment_id                   0                 0.0
order_id                     0                 0.0
payment_date                 0                 0.0
payment_method               0                 0.0
payment_status               0                 0.0
amount_paid                  0                 0.0
transaction_fee              0                 0.0
refund_amount                0                 0.0

In [5]:
duplicate_count = df.duplicated().sum()

print("Duplicate rows:", duplicate_count)

Duplicate rows: 0

In [6]:
for col in ["payment_id", "order_id"]:
    print("\n" + "=" * 50)
    print("COLUMN:", col)
    print("=" * 50)

    print("Missing:", df[col].isna().sum())
    print("Unique:", df[col].nunique(dropna=True))
    print("Repeated values:", df[col].duplicated().sum())

==================================================
COLUMN: payment_id
==================================================
Missing: 0
Unique: 20000
Repeated values: 0

==================================================
COLUMN: order_id
==================================================
Missing: 0
Unique: 20000
Repeated values: 0

In [7]:
invalid_payment_ids = ~df["payment_id"].str.startswith("PAY", na=False)
invalid_order_ids = ~df["order_id"].str.startswith("ORD", na=False)

print("Invalid payment_id format:", invalid_payment_ids.sum())
print("Invalid order_id format:", invalid_order_ids.sum())

Invalid payment_id format: 0
Invalid order_id format: 0

In [8]:
print("Payment date dtype:", df["payment_date"].dtype)
print("Missing dates:", df["payment_date"].isna().sum())

print("\nFirst 10 payment dates:")
print(df["payment_date"].head(10).tolist())

Payment date dtype: str
Missing dates: 0

First 10 payment dates:
['2024-12-14', '2024-05-26', '2023-07-22', '2023-09-22', '2024-11-24', '2025-10-28', '2024-04-24', '2023-05-07', '2025-11-03', '2025-10-22']

In [9]:
df["payment_date"] = pd.to_datetime(
    df["payment_date"],
    errors="coerce"
)

print("Payment date dtype:", df["payment_date"].dtype)
print("Invalid payment dates:", df["payment_date"].isna().sum())

print("Earliest payment date:", df["payment_date"].min())
print("Latest payment date:", df["payment_date"].max())

Payment date dtype: datetime64[us]
Invalid payment dates: 0
Earliest payment date: 2023-01-03 00:00:00
Latest payment date: 2025-12-31 00:00:00

In [10]:
categorical_columns = [
    "payment_method",
    "payment_status"
]

for col in categorical_columns:
    print("\n" + "=" * 50)
    print("COLUMN:", col)
    print("=" * 50)
    print(df[col].value_counts(dropna=False))

==================================================
COLUMN: payment_method
==================================================
payment_method
UPI                 6345
Cash on Delivery    3478
Credit Card         3040
Debit Card          2503
Net Banking         1639
Wallet              1405
EMI                  781
Pay Later            409
Gift Card            206
Cardless EMI         194
Name: count, dtype: int64

==================================================
COLUMN: payment_status
==================================================
payment_status
Success        17376
Refunded        1907
Failed           499
Not Charged      199
Pending           19
Name: count, dtype: int64

In [11]:
numeric_columns = [
    "amount_paid",
    "transaction_fee",
    "refund_amount"
]

for col in numeric_columns:
    print("\n" + "=" * 50)
    print("COLUMN:", col)
    print("=" * 50)
    print("Minimum:", df[col].min())
    print("Maximum:", df[col].max())
    print("Zero values:", (df[col] == 0).sum())
    print("Negative values:", (df[col] < 0).sum())

==================================================
COLUMN: amount_paid
==================================================
Minimum: 0.0
Maximum: 471742.11
Zero values: 717
Negative values: 0

==================================================
COLUMN: transaction_fee
==================================================
Minimum: 0.0
Maximum: 4643.1
Zero values: 14742
Negative values: 0

==================================================
COLUMN: refund_amount
==================================================
Minimum: 0.0
Maximum: 304896.9
Zero values: 18093
Negative values: 0

In [12]:
zero_amount = df[df["amount_paid"] == 0]

print("Rows with amount_paid = 0:", len(zero_amount))

print("\nPayment status for zero-payment records:")
print(
    zero_amount["payment_status"]
    .value_counts(dropna=False)
)

print("\nPayment method for zero-payment records:")
print(
    zero_amount["payment_method"]
    .value_counts(dropna=False)
)

Rows with amount_paid = 0: 717

Payment status for zero-payment records:
payment_status
Failed         499
Not Charged    199
Pending         19
Name: count, dtype: int64

Payment method for zero-payment records:
payment_method
UPI                 209
Cash on Delivery    201
Credit Card          90
Debit Card           83
Wallet               47
Net Banking          43
EMI                  21
Pay Later            10
Gift Card             9
Cardless EMI          4
Name: count, dtype: int64

In [13]:
refunded = df[df["payment_status"] == "Refunded"]

print("Refunded payment records:", len(refunded))

print(
    "Refunded records with refund_amount = 0:",
    (refunded["refund_amount"] == 0).sum()
)

print(
    "Refunded records with refund_amount > 0:",
    (refunded["refund_amount"] > 0).sum()
)

print("\nRefund amount summary for Refunded payments:")
print(refunded["refund_amount"].describe())

Refunded payment records: 1907
Refunded records with refund_amount = 0: 0
Refunded records with refund_amount > 0: 1907

Refund amount summary for Refunded payments:
count      1907.000000
mean      10066.176434
std       25593.327635
min         112.000000
25%         955.500000
50%        2381.400000
75%        6615.000000
max      304896.900000
Name: refund_amount, dtype: float64

In [14]:
non_refunded = df[df["payment_status"] != "Refunded"]

print(
    "Non-refunded records with refund_amount > 0:",
    (non_refunded["refund_amount"] > 0).sum()
)

print("\nRefund amount by payment status:")
print(
    df.groupby("payment_status")["refund_amount"]
      .agg(["count", "min", "max", "sum"])
)

Non-refunded records with refund_amount > 0: 0

Refund amount by payment status:
                count    min       max          sum
payment_status
Failed            499    0.0       0.0         0.00
Not Charged       199    0.0       0.0         0.00
Pending            19    0.0       0.0         0.00
Refunded         1907  112.0  304896.9  19196198.46
Success         17376    0.0       0.0         0.00

In [15]:
print("Transaction fee summary:")
print(df["transaction_fee"].describe())

print("\nTransaction fee by payment status:")
print(
    df.groupby("payment_status")["transaction_fee"]
      .agg(["count", "min", "max", "mean", "sum"])
)

Transaction fee summary:
count    20000.000000
mean        31.251911
std        176.050142
min          0.000000
25%          0.000000
50%          0.000000
75%          2.910000
max       4643.100000
Name: transaction_fee, dtype: float64

Transaction fee by payment status:
                count  min      max       mean        sum
payment_status
Failed            499  0.0     0.00   0.000000       0.00
Not Charged       199  0.0     0.00   0.000000       0.00
Pending            19  0.0     0.00   0.000000       0.00
Refunded         1907  0.0  4573.45  29.566691   56383.68
Success         17376  0.0  4643.10  32.726436  568654.55

In [16]:
refund_greater_than_paid = df[df["refund_amount"] > df["amount_paid"]]

print("Refund amount greater than amount paid:",
      len(refund_greater_than_paid))

if len(refund_greater_than_paid) > 0:
    print("\nExamples:")
    print(
        refund_greater_than_paid[
            ["payment_id", "order_id", "payment_status",
             "amount_paid", "refund_amount"]
        ].head(10)
    )

Refund amount greater than amount paid: 0

In [17]:
numeric_cols = ["amount_paid", "transaction_fee", "refund_amount"]

for col in numeric_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = df[
        (df[col] < lower_bound) |
        (df[col] > upper_bound)
    ]

    print(f"\n{col}")
    print("Q1:", Q1)
    print("Q3:", Q3)
    print("IQR:", IQR)
    print("Lower bound:", lower_bound)
    print("Upper bound:", upper_bound)
    print("Outlier count:", len(outliers))

amount_paid
Q1: 836.04
Q3: 6357.202499999999
IQR: 5521.162499999999
Lower bound: -7445.70375
Upper bound: 14638.946249999999
Outlier count: 2681

transaction_fee
Q1: 0.0
Q3: 2.91
IQR: 2.91
Lower bound: -4.365
Upper bound: 7.275
Outlier count: 4392

refund_amount
Q1: 0.0
Q3: 0.0
IQR: 0.0
Lower bound: 0.0
Upper bound: 0.0
Outlier count: 1907

In [18]:
print("FINAL INTEGRITY CHECK")
print("=" * 50)

print("Original shape:", df_original.shape)
print("Current shape:", df.shape)

print("Rows removed:", len(df_original) - len(df))
print("Columns removed:", len(df_original.columns) - len(df.columns))

print("\nDuplicate rows:", df.duplicated().sum())
print("Total missing values:", df.isna().sum().sum())

print("\nColumn names:")
print(df.columns.tolist())

print("\nData types:")
print(df.dtypes)

FINAL INTEGRITY CHECK
==================================================
Original shape: (20000, 8)
Current shape: (20000, 8)
Rows removed: 0
Columns removed: 0

Duplicate rows: 0
Total missing values: 0

Column names:
['payment_id', 'order_id', 'payment_date', 'payment_method', 'payment_status', 'amount_paid', 'transaction_fee', 'refund_amount']

Data types:
payment_id                    str
order_id                      str
payment_date       datetime64[us]
payment_method                str
payment_status                str
amount_paid               float64
transaction_fee           float64
refund_amount             float64
dtype: object

In [19]:
output_file = "payments_cleaned.csv"

df.to_csv(output_file, index=False)

print("Saved successfully:", output_file)

Saved successfully: payments_cleaned.csv

In [20]:
import os

print("File exists:", os.path.exists(output_file))

if os.path.exists(output_file):
    print("File size:", os.path.getsize(output_file), "bytes")
    
    check_df = pd.read_csv(output_file)
    print("Saved file shape:", check_df.shape)
    print("Saved file columns:", check_df.columns.tolist())

File exists: True
File size: 1355351 bytes
Saved file shape: (20000, 8)
Saved file columns: ['payment_id', 'order_id', 'payment_date', 'payment_method', 'payment_status', 'amount_paid', 'transaction_fee', 'refund_amount']